export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const SET_TEMPERATURE_UNIT = 'SET_TEMPERATURE_UNIT';
export const CONVERT_FAVORITE_DEGREE = 'CONVERT_FAVORITE_DEGREE';
